name: CI
on:
  push:
    branches:
      main
  pull_request:
jobs:
  flake-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
            substituters = https://cache.iog.io
      - uses: cachix/cachix-action@v16
        with:
          name: jisantuc
          authToken: '${{ secrets.CACHIX_TOKEN }}'
      - run: nix develop .#ci --command ./scripts/test
      - name: Generate coverage report
        uses: 8c6794b6/hpc-codecov-action@v4
        with:
          target: cabal:project-name-test
          excludes: |
            Test.Data.Okasaki.BinaryTreeSpec
      - name: Send coverage report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
